import { useState } from 'react'
import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs'
import { Bars3Icon } from '@heroicons/react/24/solid'
import Head from 'next/head'

import { api } from '~/utils/api'
import type { RouterOutputs } from '~/utils/api'
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
dayjs.extend(relativeTime)

type FactlieWithUser = RouterOutputs['factlies']['getAll'][number]
const FactlieView = (props: FactlieWithUser) => {
  const { factlie, author } = props
  
  return (
    <li key={factlie.id} className='text-slate-900 border-b border-slate-900 p-8 w-1/2 flex-col bg-white'>
      <div className='flex gap-4'>
        <img src={author.profileImageUrl} alt={author.id} className='h-9 w-9 rounded-full' />
        <div>
          <h2 className='text-base'>{author.username}</h2>
          <sup className='text-sm'>{dayjs(factlie.createdAt).fromNow()}</sup>
        </div>
      </div>
      <div>
        <p>Fact: {factlie.fact}</p>
        <p>Fact Author: {factlie.factAuthor}</p>
        <p>Fact Url: {factlie.factUrl}</p>
        <br />
        <p>Lie: {factlie.lie}</p>
        <p>Lie Author: {factlie.lieAuthor}</p>
        <p>Lie Url: {factlie.lieUrl}</p>
      </div>
    </li>
  )
}

export default function Home() {
  const user = useUser()
  const { data, isLoading } = api.factlies.getAll.useQuery()
  if(isLoading) return <div>Loading...</div>
  if(!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Factlie</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center justify-center bg-[#F6F6F6] light'>
        <header className='w-full border-b flex p-3 text-slate-900 mb-4 border-slate-800'>
          <Bars3Icon className='h-6 w-6' />
          <h1 className='ml-2'>Factlie</h1>
          {/* <nav className='text-sm flex'>
            <div className='text-slate-900'>{user.isSignedIn && <SignOutButton />}</div>
            <div className='text-slate-900'>{!user.isSignedIn && <SignInButton />}</div>
          </nav> */}
        </header>
        <div className='text-slate-900 w-full px-4'>{user.isSignedIn && createFactlieWizard()}</div>
        <ul className='flex w-full'>
          {[...data, ...data]?.map((fullFactlie) => (
            <FactlieView {...fullFactlie} key={fullFactlie.factlie.id} />
          ))}
        </ul>
      </main>
    </>
  )
}

const createFactlieWizard = () => {
  const { user } = useUser()

  if( !user ) {
    return null
  }

  return (
    <div className='flex gap-3 w-full border border-pink-400 p-2 mb-4'>
      <img src={user.imageUrl} alt={user.id} className='h-10 w-10 rounded-full' />
      <input placeholder='Add a Factlie' className='bg-transparent outline-none w-full block' />
    </div>
  )
}